### ISSUE TITLE
lỗi file dữ liệu đầu vào với Python

### ISSUE THREAD

**Issue by Anhcuseu19072004** [Belikhun/themis-web-interface#71]
![image](https://user-images.githubusercontent.com/90545183/148250085-cf5ab6fb-dc62-4aad-82ea-5b3d4ff30e95.png)
![image](https://user-images.githubusercontent.com/90545183/148250739-20501339-d25e-48cc-8d88-760936547094.png)

![image](https://user-images.githubusercontent.com/90545183/148250162-a2591cf0-a3d6-42cc-a6e2-38ef1a276b87.png)
![image](https://user-images.githubusercontent.com/90545183/148250201-0d2c725b-0a9f-4ad7-a20a-f1959db3b434.png)
![image](https://user-images.githubusercontent.com/90545183/148250412-3345519e-a60e-42a8-9a86-1d62a8434e34.png)

theo yêu cầu đề bài thì không cần thêm dường dẫn tuyệt đối cho file, và themis không nhấc được file dữ liệu vào cho python sử lý

**Comment by Belikhun** [comment]
Xin lỗi bạn nhưng đây là lỗi của trình chấm themis, mình không phụ trách về phần này. Bạn có thể gửi câu hỏi hoặc đường dẫn tới issue này vào phần bình luận của [trang blog gốc](https://dsapblog.wordpress.com/2013/12/24/themis/) để nhận trợ giúp nhé.
