### ISSUE TITLE
Về Format điểm

### ISSUE THREAD

**Issue by ppap-1264589** [Belikhun/themis-web-interface#72]
## 🙋‍♀️ hỏi đáp
---
### ❓ Câu Hỏi
Làm sao để điểm của server trả về cho thí sinh hiện đúng phần thập phân như trong Themis ạ 🔢 
Ví dụ, trong Themis của em đặt điểm của mỗi test là 0.175 điểm, nhưng trên server chỉ hiện 0.17 điểm ạ

#### Thông tin thêm
![Capture](https://user-images.githubusercontent.com/88699088/159157815-6ea322e5-8784-4e69-949b-e9d86c8502b4.PNG)
![THEMIS](https://user-images.githubusercontent.com/88699088/159157816-8bedc547-2400-4078-a4f9-d9a27de2876c.PNG)

**Comment by Belikhun** [comment]
Bạn sửa ở [`/lib/logParser.php:233`](https://github.com/Belikhun/themis-web-interface/blob/a78daba7af98345ad19b166c89549222b02fcc6d/lib/logParser.php#L233) nha.

```diff
private function __f($str) {
-    return round((float) str_replace(",", ".", $str), 2);
+    return round((float) str_replace(",", ".", $str), 3);
}
```
