### ISSUE TITLE
Về output format của logs

### ISSUE THREAD

**Issue by ppap-1264589** [Belikhun/themis-web-interface#73]
## 🙋‍♀️ hỏi đáp
---
### ❓ Câu Hỏi
Làm sao để mình in được số 100 của logs trên 1 dòng đây ạ :Đ

#### Thông tin thêm
![ti](https://user-images.githubusercontent.com/88699088/159165926-1dda8201-e717-4497-9088-ab3ab766a04d.PNG)

**Comment by Belikhun** [comment]
Bạn chỉnh ở [`/static/css/core.css:2334`](https://github.com/Belikhun/themis-web-interface/blob/v0.6.0-rev3/static/css/core.css#L2334) nha.

```diff
.viewLog-container .testList .item .line .left .testid::before {
    content: "#"counter(testItem);
    position: relative;
    display: inline-block;
    font-size: 11px;
-   width: 25px;
+   min-width: 25px;
}
```
