### ISSUE TITLE
Bao giờ có bản mới vậy bạn?

### ISSUE THREAD

**Issue by QuangIT2309** [Belikhun/themis-web-interface#76]
## 🙋‍♀️ hỏi đáp
---
### ❓ Câu Hỏi
Viết câu hỏi của bạn tại đây ヾ(•ω•`)o

#### Thông tin thêm
Thêm bất kỳ thông tin nào liên quan tại đây.

**Comment by QuangIT2309** [comment]
Trước Tết bạn nói sau Tết sẽ cập nhật bản mới, chờ qua tháng 2 rồi chưa thấy ...

**Comment by Belikhun** [comment]
Sorry bạn hiện mình chưa thể sắp xếp thời gian cho project này được. Sau khi hoàn thành xong công việc hiện tại mình sẽ dành thời gian thêm cho project này.
