### ISSUE TITLE
Lỗi tạo tài khoản thiết lập

### ISSUE THREAD

**Issue by duongnotnhan** [Belikhun/themis-web-interface#77]
## 🐞 báo cáo lỗi
---
### 📃 Mô Tả
Lúc đang thiết lập hệ thống và đăng kí tài khoản thì nó bị như thế này

### 🔬 Cách Gây Ra Lỗi
1. Đi tới 'setup.php'
2. Nhấn vào 'thiết lập' & 'tạo tài khoản'
3. Kết quả trả về: [-1] Error Occurred: Creation of dynamic property Account::$username is deprecated

### 📷 Ảnh Chụp
![image](https://github.com/Belikhun/themis-web-interface/assets/98535924/d5c7c6a7-5af4-446d-a1a1-ecaec3bd1fb8)

### 🌍 Phiên Bản
 - Hệ điều hành: Windows 11
 - Trình duyệt: FireFox
 - Trình chấm: chưa dùng

**Comment by Belikhun** [comment]
Bạn dùng php 8.1 trở xuống nha.
