### ISSUE TITLE
Lỗi không truy cập được

### ISSUE THREAD

**Issue by QuangIT2309** [Belikhun/themis-web-interface#78]
## 🐞 báo cáo lỗi
---
### 📃 Mô Tả
Một mô tả ngắn gọn và rõ ràng về lỗi mà bạn gặp

### 🔬 Cách Gây Ra Lỗi
1. Mở Uniserver
2. Nhấn vào Start Apacher
3. Trang web xuất hiện.'
4. Lỗi!!!

### 🎯 Hành Vi Dự Kiến
Một mô tả rõ ràng và ngắn gọn về hành vi mà bạn nghĩ nên xảy ra

### 📷 Ảnh Chụp
Nếu có thể, hãy đính kèm một ảnh chụp màn hình tại đây.
![image](https://github.com/Belikhun/themis-web-interface/assets/39910902/19ce6271-45fe-4d34-ba9e-998b93de112c)

### 🌍 Phiên Bản
 - Hệ điều hành: [vd: Windows, Ubuntu, MacOS]
 - Trình duyệt: [vd: Chrome, CocCoc, Edge, Safari]
 - Trình chấm: [vd: Themis v1.9.8 b.2806]

#### Thông tin thêm
Thêm bất kỳ thông tin nào liên quan đến lỗi tại đây.

**Comment by Belikhun** [comment]
Bạn sao chép thông tin lỗi rồi gửi cho mình xem nha.
