### ISSUE TITLE
Xoá toàn bộ điểm ở trong contest

### ISSUE THREAD

**Issue by LaziChicken7** [Belikhun/themis-web-interface#79]
## 🙋‍♀️ hỏi đáp
---
### ❓ Câu Hỏi
Có cách nào để xoá toàn bộ điểm / 1 số điểm trong contest không ạ?

#### Thông tin thêm
Thêm bất kỳ thông tin nào liên quan tại đây.

**Comment by Belikhun** [comment]
Với `v0.6` thì bạn đi tới vị trí thư mục `uploadDir`, trong thư mục này sẽ có 1 thư mục `Logs`, bạn vào đây và xóa những file log tương ứng với bài nộp mà bạn muốn xóa trên hệ thống. Còn với `v1.0` thì đã có sẵn nút để xóa toàn bộ điểm ở trong bảng cài đặt của admin, hoặc xóa điểm của từng người một trong thư mục `submissions` bên trong `uploadDir` nhé.
