### ISSUE TITLE
Lỗi 500

### ISSUE THREAD

**Issue by duckbp4ever** [Belikhun/themis-web-interface#80]
## 🐞 báo cáo lỗi
---
### 📃 Mô Tả
Không vào được web

### 🔬 Cách Gây Ra Lỗi
Đăng nhập quyền admin

### 🎯 Hành Vi Dự Kiến
E cài trên cả 2 máy đều bị lỗi 😭

### 📷 Ảnh Chụp
![image](https://github.com/Belikhun/themis-web-interface/assets/114001224/30ee6f83-fe17-4a99-9adb-472a0e448a71)

### 🌍 Phiên Bản
 - Hệ điều hành: Windows
 - Trình duyệt: CocCoc
 - Trình chấm: Còn chưa mở Themis

#### Thông tin thêm
Thêm bất kỳ thông tin nào liên quan đến lỗi tại đây.
![image](https://github.com/Belikhun/themis-web-interface/assets/114001224/ca86cadd-d7e8-4f19-bdad-c143e664fe8e)

**Comment by Belikhun** [comment]
Bạn thử xóa file `data/config.json` và thử lại nhé

**Comment by duckbp4ever** [comment]
![image](https://github.com/Belikhun/themis-web-interface/assets/114001224/450bf1ad-a59c-42ed-8f98-04a97236c615)
vẫn không đc a ạ
![image](https://github.com/Belikhun/themis-web-interface/assets/114001224/5134be3d-5d6c-468c-a995-183c15535bf1)

**Comment by duckbp4ever** [comment]
e đã thử xóa 1 lần nz r tải lại và vẫn k đc

**Comment by Belikhun** [comment]
bạn thử lấy file `config.json` bên trong file zip bạn tải về và vứt vào thư mục `data` xem nhé
